package br.com.maplink.calculadorvaloresrotas.model.veiculo;

import br.com.maplink2.webservices.Vehicle;

/**
 * 
 * @author luizleme
 *
 */
public interface IVeiculo {
	public enum NumeroEixosPorTipoVeiculo {
		
		ISENTO(0),
		MOTOCICLETAS_MOTONETAS_E_BICICLETASAMOTOR(1),
		AUTOMOVEL_CAMINHONETA_FURGAO(2),
		AUTOMOVEL_CAMINHONETA_COM_SEMIREBOQUE(3),
		AUTOMOVEL_CAMINHONETA_COM_REBOQUE(4),
		ONIBUS(5),
		ONIBUS_COM_REBOQUE(6),
		CAMINHAOLEVE_FURGAO_CAVALOMECANICO(7),
		CAMINHAO_CAMINHAOTRATOR_CAVALOMECANICO_COM_SEMIREBOQUE(8),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE(9),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE_CINCO_EIXOS_DUPLOS(10),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE_SEIS_EIXOS_DUPLOS(11),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE_SETE_EIXOS_DUPLOS(12),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE_OITO_EIXOS_DUPLOS(13),
		CAMINHAO_COM_REBOQUE_CAVALOMECANICO_COM_SEMIREBOQUE_NOVE_EIXOS_DUPLOS(14);
		
		private final int valor;

		NumeroEixosPorTipoVeiculo(int valorOpcao) {
			valor = valorOpcao;
		}

		public int getValor() {
			return valor;
		}
	}

	
	Vehicle obterVeiculo();

}
